
server:
  port: '8086'

spring:
  profiles:
    active: qa

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!

---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: hbstudent
    url: jdbc:mysql://localhost:3306/dcbapp-qa?useSSL=false
    password: hbstudent
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Daily Code Buffer!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: hbstudent
    url: jdbc:mysql://localhost:3306/dcbapp-prod?useSSL=false
    password: hbstudent
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Daily Code Buffer!!
